# ============================================================================
# MEDIROUTE APPLICATION CONFIGURATION
# ============================================================================

spring:
  application:
    name: mediroute

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/mediroute
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Changed from create-drop for development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  # Liquibase - DISABLED for now to avoid conflicts
  liquibase:
    enabled: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Denver

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# External Services
google:
  api:
    key:

osrm:
  base-url: http://localhost:5000

# MediRoute Specific
mediroute:
  depot-distance: 10
  mph-factor: 120

# Logging
logging:
  level:
    com.mediroute: DEBUG
    org.hibernate.SQL: WARN
    org.springframework.web: WARN

# Server
server:
  port: 8080

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.mediroute: TRACE