----liquibase formatted sql
--
----changeset semere:004-fix-assignment-audit-id
--
---- Alter the ID column from SERIAL/INT to BIGSERIAL/BIGINT
--ALTER TABLE assignment_audit
--    ALTER COLUMN id TYPE BIGINT;
--
---- Reset sequence if it exists
--DO $$
--BEGIN
--    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'assignment_audit_id_seq') THEN
--        EXECUTE 'ALTER SEQUENCE assignment_audit_id_seq AS BIGINT';
--    END IF;
--END;
--$$;